version: '3'
services:
  web2: 
    image: java_springv3
    build: .
    ports:
      - "8087:8085"
    volumes:
      - persistent_volume:/app/volumes
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/projects/jaysspring/volumes
